### ISSUE TITLE
`Sketchpad.Repo` does not exist

### ISSUE THREAD

**Issue by lukeed** [chrismccord/sketchpad#1]
Cannot run migrations because `Sketchpad.Repo` can't be loaded.

```
** (Mix) Could not load Sketchpad.Repo, error: :nofile. Please configure your app accordingly or pass a repo with the -r option.
```

**Comment by ajrobertsonio** [comment]
I have a fix for this on my github, https://github.com/codeithuman/sketchpad/commit/c9f1d7074fcf528db9a2ed5b3b10c5b907fe1395. 

Sorry it's not an official PR, I can probably submit one in the morning.

**Comment by chrismccord** [comment]
Fixed. Thanks!
